### ISSUE TITLE
No such file or directory github-circleci-trigger/requirements

### ISSUE THREAD

**Issue by JienLee** [Slicer/github-circleci-trigger#3]
When I run this command "pip install -r github-circleci-trigger/requirements",
it show the message "Could not open requirements file : No such file or directory~ ..".

What can I do?

**Comment by jcfr** [comment]
Thanks for reporting the problem. 

I fixed the instructions listed in the README file.

It should be:

```
pip install -r github-circleci-trigger/requirements.txt
```
